import type { Metadata } from "next";

import { COMPANY_DEFAULTS } from "@/config/company-defaults";
import { SITE_TAGLINE } from "@/config/marketing-content";

// Next.js replaces (does not merge) a parent's `openGraph` / `twitter` when a page sets
// its own, so every page spreads these shared values. The images are generated by
// app/opengraph-image.tsx and app/twitter-image.tsx.
const SHARE_IMAGE_ALT = `${COMPANY_DEFAULTS.displayName}: ${SITE_TAGLINE} Call ${COMPANY_DEFAULTS.phone}.`;

export const SHARED_OPEN_GRAPH = {
  type: "website",
  siteName: COMPANY_DEFAULTS.displayName,
  locale: "en_CA",
  images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: SHARE_IMAGE_ALT }],
} satisfies Metadata["openGraph"];

export const SHARED_TWITTER = {
  card: "summary_large_image",
  images: [{ url: "/twitter-image", alt: SHARE_IMAGE_ALT }],
} satisfies Metadata["twitter"];

// Title, description and canonical path for one public page, with the shared share card.
export function pageSocialMetadata(title: string, description: string, path: string): Metadata {
  return {
    alternates: { canonical: path },
    openGraph: { ...SHARED_OPEN_GRAPH, title, description, url: path },
    twitter: { ...SHARED_TWITTER, title, description },
  };
}
