import type { DocumentType } from "@/generated/prisma/enums";

export const DOCUMENT_TYPE_LABELS: Record<DocumentType, string> = {
  CARRIER_RATE_CONFIRMATION: "Carrier Load Confirmation",
  SHIPPER_RATE_CONFIRMATION: "Customer Rate Confirmation",
  BOL: "Bill of Lading",
  POD: "POD — Proof of Delivery",
  COD: "COD / Delivery Document",
  INVOICE: "Invoice",
  RECEIPT: "Receipt",
  LUMPER_RECEIPT: "Lumper Receipt",
  SCALE_TICKET: "Scale Ticket",
  GATE_TICKET: "Gate / Interchange Ticket",
  CUSTOMS_DOCUMENT: "Customs Document",
  OTHER: "Other",
};

// Generated by the system from load data (versioned).
export const GENERATED_DOCUMENT_TYPES = [
  "CARRIER_RATE_CONFIRMATION",
  "SHIPPER_RATE_CONFIRMATION",
  "BOL",
] as const satisfies readonly DocumentType[];

export type GeneratedDocumentType = (typeof GENERATED_DOCUMENT_TYPES)[number];

// Uploaded by staff (POD first — it is the most common).
export const UPLOADABLE_DOCUMENT_TYPES = [
  "POD",
  "COD",
  "GATE_TICKET",
  "SCALE_TICKET",
  "LUMPER_RECEIPT",
  "RECEIPT",
  "INVOICE",
  "CUSTOMS_DOCUMENT",
  "OTHER",
] as const satisfies readonly DocumentType[];

export type UploadableDocumentType = (typeof UPLOADABLE_DOCUMENT_TYPES)[number];

// Documents that contain rates: only users with `financials:read` may open them.
export const FINANCIAL_DOCUMENT_TYPES: readonly DocumentType[] = [
  "CARRIER_RATE_CONFIRMATION",
  "SHIPPER_RATE_CONFIRMATION",
  "INVOICE",
];

// Generated file name slug: 100001-carrier-rate-confirmation-v1.pdf
export const GENERATED_FILE_SLUGS: Record<GeneratedDocumentType, string> = {
  CARRIER_RATE_CONFIRMATION: "carrier-rate-confirmation",
  SHIPPER_RATE_CONFIRMATION: "shipper-rate-confirmation",
  BOL: "bol",
};

export function isGeneratedDocumentType(value: string): value is GeneratedDocumentType {
  return (GENERATED_DOCUMENT_TYPES as readonly string[]).includes(value);
}

export function isUploadableDocumentType(value: string): value is UploadableDocumentType {
  return (UPLOADABLE_DOCUMENT_TYPES as readonly string[]).includes(value);
}
