export const AUDIT_ACTIONS = {
  LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",

  CLIENT_CREATED: "CLIENT_CREATED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_ARCHIVED: "CLIENT_ARCHIVED",

  CARRIER_CREATED: "CARRIER_CREATED",
  CARRIER_UPDATED: "CARRIER_UPDATED",
  CARRIER_ARCHIVED: "CARRIER_ARCHIVED",

  DRIVER_CREATED: "DRIVER_CREATED",
  DRIVER_UPDATED: "DRIVER_UPDATED",

  LOAD_CREATED: "LOAD_CREATED",
  LOAD_UPDATED: "LOAD_UPDATED",
  LOAD_DELETED: "LOAD_DELETED",
  CLIENT_RATE_CHANGED: "CLIENT_RATE_CHANGED",
  CARRIER_RATE_CHANGED: "CARRIER_RATE_CHANGED",
  STATUS_CHANGED: "STATUS_CHANGED",
  LOAD_CHARGE_ADDED: "LOAD_CHARGE_ADDED",
  LOAD_CHARGE_REMOVED: "LOAD_CHARGE_REMOVED",

  DOCUMENT_GENERATED: "DOCUMENT_GENERATED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",

  COMPANY_SETTINGS_UPDATED: "COMPANY_SETTINGS_UPDATED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITIES = {
  USER: "User",
  CLIENT: "Client",
  CARRIER: "Carrier",
  DRIVER: "Driver",
  LOAD: "Load",
  DOCUMENT: "Document",
  COMPANY_SETTINGS: "CompanySettings",
} as const;

export type AuditEntity = (typeof AUDIT_ENTITIES)[keyof typeof AUDIT_ENTITIES];
